# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import inference_pb2 as inference__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InferenceServiceStub(object):
    """InferenceService defines the gRPC service for LLM inference
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Inference = channel.unary_unary(
                '/inference.InferenceService/Inference',
                request_serializer=inference__pb2.InferenceRequest.SerializeToString,
                response_deserializer=inference__pb2.InferenceResponse.FromString,
                _registered_method=True)
        self.StreamInference = channel.unary_stream(
                '/inference.InferenceService/StreamInference',
                request_serializer=inference__pb2.InferenceRequest.SerializeToString,
                response_deserializer=inference__pb2.InferenceStreamResponse.FromString,
                _registered_method=True)
        self.LoadModel = channel.unary_unary(
                '/inference.InferenceService/LoadModel',
                request_serializer=inference__pb2.LoadModelRequest.SerializeToString,
                response_deserializer=inference__pb2.LoadModelResponse.FromString,
                _registered_method=True)
        self.UnloadModel = channel.unary_unary(
                '/inference.InferenceService/UnloadModel',
                request_serializer=inference__pb2.UnloadModelRequest.SerializeToString,
                response_deserializer=inference__pb2.UnloadModelResponse.FromString,
                _registered_method=True)
        self.GetModelInfo = channel.unary_unary(
                '/inference.InferenceService/GetModelInfo',
                request_serializer=inference__pb2.GetModelInfoRequest.SerializeToString,
                response_deserializer=inference__pb2.GetModelInfoResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/inference.InferenceService/HealthCheck',
                request_serializer=inference__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=inference__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class InferenceServiceServicer(object):
    """InferenceService defines the gRPC service for LLM inference
    """

    def Inference(self, request, context):
        """Inference performs synchronous inference
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamInference(self, request, context):
        """StreamInference performs streaming inference
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadModel(self, request, context):
        """LoadModel loads a model into memory
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnloadModel(self, request, context):
        """UnloadModel unloads a model from memory
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelInfo(self, request, context):
        """GetModelInfo retrieves information about a loaded model
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """HealthCheck checks the health of the inference worker
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Inference': grpc.unary_unary_rpc_method_handler(
                    servicer.Inference,
                    request_deserializer=inference__pb2.InferenceRequest.FromString,
                    response_serializer=inference__pb2.InferenceResponse.SerializeToString,
            ),
            'StreamInference': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamInference,
                    request_deserializer=inference__pb2.InferenceRequest.FromString,
                    response_serializer=inference__pb2.InferenceStreamResponse.SerializeToString,
            ),
            'LoadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadModel,
                    request_deserializer=inference__pb2.LoadModelRequest.FromString,
                    response_serializer=inference__pb2.LoadModelResponse.SerializeToString,
            ),
            'UnloadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.UnloadModel,
                    request_deserializer=inference__pb2.UnloadModelRequest.FromString,
                    response_serializer=inference__pb2.UnloadModelResponse.SerializeToString,
            ),
            'GetModelInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelInfo,
                    request_deserializer=inference__pb2.GetModelInfoRequest.FromString,
                    response_serializer=inference__pb2.GetModelInfoResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=inference__pb2.HealthCheckRequest.FromString,
                    response_serializer=inference__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inference.InferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inference.InferenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InferenceService(object):
    """InferenceService defines the gRPC service for LLM inference
    """

    @staticmethod
    def Inference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inference.InferenceService/Inference',
            inference__pb2.InferenceRequest.SerializeToString,
            inference__pb2.InferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamInference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/inference.InferenceService/StreamInference',
            inference__pb2.InferenceRequest.SerializeToString,
            inference__pb2.InferenceStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inference.InferenceService/LoadModel',
            inference__pb2.LoadModelRequest.SerializeToString,
            inference__pb2.LoadModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnloadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inference.InferenceService/UnloadModel',
            inference__pb2.UnloadModelRequest.SerializeToString,
            inference__pb2.UnloadModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inference.InferenceService/GetModelInfo',
            inference__pb2.GetModelInfoRequest.SerializeToString,
            inference__pb2.GetModelInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inference.InferenceService/HealthCheck',
            inference__pb2.HealthCheckRequest.SerializeToString,
            inference__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
