"""
VelocityLLM Python Worker - Lightweight Test Version
Tests gRPC functionality without requiring vLLM
"""

import asyncio
import grpc
from concurrent import futures
import time
import sys
import os
from loguru import logger

# Add proto path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'internal', 'grpc', 'pb'))

try:
    import inference_pb2
    import inference_pb2_grpc
except ImportError:
    logger.error("Failed to import protobuf files. Make sure they are generated.")
    logger.info("Run: python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. inference.proto")
    sys.exit(1)


class MockInferenceService(inference_pb2_grpc.InferenceServiceServicer):
    """Mock inference service for testing"""

    def __init__(self):
        self.request_count = 0
        logger.info("Mock Inference Service initialized")

    async def GenerateText(self, request, context):
        """Handle text generation request"""
        self.request_count += 1
        request_id = self.request_count

        logger.info(f"[Request {request_id}] Received inference request")
        logger.info(f"  Model: {request.model}")
        logger.info(f"  Prompt: {request.prompt[:100]}...")
        logger.info(f"  Max tokens: {request.max_tokens}")
        logger.info(f"  Temperature: {request.temperature}")

        # Simulate processing time
        await asyncio.sleep(0.5)

        # Generate mock response
        response_text = f"This is a mock response from the Python worker for prompt: '{request.prompt[:50]}...'. "
        response_text += f"In production, this would be generated by vLLM using the {request.model} model. "
        response_text += f"Request ID: {request_id}"

        # Create response
        response = inference_pb2.InferenceResponse(
            request_id=str(request_id),
            text=response_text,
            tokens_used=len(response_text.split()),
            latency_ms=500,
            model=request.model,
            success=True
        )

        logger.success(f"[Request {request_id}] Generated {response.tokens_used} tokens in {response.latency_ms}ms")
        return response

    async def GenerateTextStream(self, request, context):
        """Handle streaming text generation"""
        self.request_count += 1
        request_id = self.request_count

        logger.info(f"[Stream {request_id}] Received streaming request")
        logger.info(f"  Model: {request.model}")
        logger.info(f"  Prompt: {request.prompt[:100]}...")

        # Simulate streaming tokens
        mock_tokens = [
            "This ", "is ", "a ", "mock ", "streaming ", "response ",
            "from ", "the ", "Python ", "worker. ", "In ", "production, ",
            "this ", "would ", "stream ", "tokens ", "from ", "vLLM. ",
            f"Request ", f"ID: ", f"{request_id}"
        ]

        for i, token in enumerate(mock_tokens):
            # Simulate token generation delay
            await asyncio.sleep(0.1)

            chunk = inference_pb2.StreamChunk(
                request_id=str(request_id),
                token=token,
                index=i,
                is_final=(i == len(mock_tokens) - 1)
            )

            logger.debug(f"[Stream {request_id}] Sending token {i}: {token}")
            yield chunk

        logger.success(f"[Stream {request_id}] Stream completed - sent {len(mock_tokens)} tokens")

    async def HealthCheck(self, request, context):
        """Health check endpoint"""
        logger.debug("Health check received")

        return inference_pb2.HealthResponse(
            status="healthy",
            message="Mock worker is running",
            uptime_seconds=int(time.time() - start_time),
            model_loaded=True,
            gpu_available=False,
            gpu_memory_used=0,
            gpu_memory_total=0
        )


async def serve():
    """Start the gRPC server"""
    server = grpc.aio.server(futures.ThreadPoolExecutor(max_workers=10))

    # Add service
    inference_service = MockInferenceService()
    inference_pb2_grpc.add_InferenceServiceServicer_to_server(
        inference_service, server
    )

    # Listen on port 50051
    port = "50051"
    server.add_insecure_port(f"[::]:{port}")

    logger.info(f"Starting Mock Python Worker on port {port}")
    logger.info("=" * 60)
    logger.info("This is a LIGHTWEIGHT TEST VERSION")
    logger.info("For production, use the full worker with vLLM")
    logger.info("=" * 60)

    await server.start()
    logger.success(f"✅ Mock Worker listening on port {port}")
    logger.info("Ready to accept gRPC requests from Go backend")
    logger.info("Press Ctrl+C to stop")

    try:
        await server.wait_for_termination()
    except KeyboardInterrupt:
        logger.info("Shutting down...")
        await server.stop(5)


if __name__ == "__main__":
    # Configure logger
    logger.remove()
    logger.add(
        sys.stderr,
        format="<green>{time:HH:mm:ss}</green> | <level>{level: <8}</level> | <level>{message}</level>",
        level="INFO",
        colorize=True
    )

    start_time = time.time()

    logger.info("🚀 VelocityLLM Python Worker - Test Mode")
    logger.info("=" * 60)

    # Run server
    try:
        asyncio.run(serve())
    except Exception as e:
        logger.error(f"Failed to start server: {e}")
        sys.exit(1)
